import React from 'react';
import { Box, Button, Main } from 'grommet';
import type { NextPage } from 'next';
import Head from 'next/head';

import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Athena - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main pad="large">
        <Box
          direction="row"
          border={{ color: 'brand', size: 'large' }}
          pad="medium"
          fill
          gap="small"
          justify="center"
        >
          <Link href="/login">
            <Button label="Sign in" />
          </Link>

          <Link href="/sign-up">
            <Button primary label="Sign up" />
          </Link>
        </Box>
      </Main>
    </div>
  );
};

export default Home;
