import React from 'react';
import { Box, Button, Main } from 'grommet';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Athena - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main background="brand">
        <Box direction="column" justify="center" align="center">
          <Box margin={{ vertical: 'large' }}>
            <Image src="/athena-logo.svg" width={300} height={300} />
          </Box>

          <Box direction="column" width="medium" justify="center" gap="small">
            <Link href="/login">
              <Button label="Sign in" />
            </Link>

            <Link href="/sign-up">
              <Button primary label="Sign up" />
            </Link>
          </Box>
        </Box>
      </Main>
    </>
  );
};

export default Home;
